SELECT * FROM emp_mgmt.emp;

select * from dept;

#1. INNER JOIN : COMMON IN BOTH TABLES ONLY
SELECT * FROM EMP E INNER JOIN DEPT D ON E.DEPTID=D.DEPTID;

#2. LEFT JOIN : ALL OF LEFT + ONLY MATCHING OF RIGHT AND NULL FOR NOT MATCHING
SELECT * FROM EMP E LEFT JOIN DEPT D ON E.DEPTID=D.DEPTID;

#3. LEFT JOIN WITH NULL ON RIGHT : ONLY UNIQUE TO LEFT  
SELECT * FROM EMP E LEFT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE D.DEPTID IS NULL;

#4. LEFT JOIN WITH NOT NULL ON RIGHT : ALL OF LEFT + ONLY MATCHING OF RIGHT
SELECT * FROM EMP E LEFT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE D.DEPTID IS NOT NULL;

#5. RIGHT JOIN : ALL OF RIGHT + ONLY MATHCING OF LEFT AND NULL FOR NOT MATCHING
SELECT * FROM EMP E RIGHT JOIN DEPT D ON E.DEPTID=D.DEPTID;

#6. RIGHT JOIN WITH NULL ON LEFT : ONLY UNIQUE TO RIGHT
SELECT * FROM EMP E RIGHT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE E.DEPTID IS NULL;

#7. RIGHT JOIN WITH NOT NULL ON LEFT : ALL OF LEFT + ONLY MATCHING OF RIGHT
SELECT * FROM EMP E RIGHT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE E.DEPTID IS NOT NULL;

#8. FULL OUTER JOIN = LEFT + RIGHT + UNION
SELECT * FROM EMP E LEFT JOIN DEPT D ON E.DEPTID=D.DEPTID
UNION
SELECT * FROM EMP E RIGHT JOIN DEPT D ON E.DEPTID=D.DEPTID;

#8. FULL OUTER JOIN = LEFT + RIGHT + UNION
SELECT * FROM EMP E LEFT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE E.DEPTID IS NULL OR D.DEPTID IS NULL
UNION
SELECT * FROM EMP E RIGHT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE E.DEPTID IS NULL OR D.DEPTID IS NULL;
