SELECT * FROM emp_mgmt.emp;
#1	Ashwin	Mumbai		50	-1
#2	Shweta	Mumbai		51	1
#3	Milind	Panvel		51	1
#4	Jag		Jog				2
#5	kavya	New Panvel	53	4
#6	Akshit	NNP			53	4

select * from dept;
#50	IT
#51	BANK
#52	HR
#53	School

#INNER JOIN : COMMON IN BOTH TABLES ONLY
SELECT * FROM EMP E INNER JOIN DEPT D ON E.DEPTID=D.DEPTID;

#LEFT JOIN : ALL OF LEFT + ONLY MATCHING OF RIGHT
SELECT * FROM EMP E LEFT JOIN DEPT D ON E.DEPTID=D.DEPTID;

#LEFT JOIN WITH NULL ON RIGHT : ONLY NOT MATCHING OF LEFT  
SELECT * FROM EMP E LEFT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE D.DEPTID IS NULL;

#RIGHT JOIN : ALL OF RIGHT + ONLY MATHCING OF LEFT
SELECT * FROM EMP E RIGHT JOIN DEPT D ON E.DEPTID=D.DEPTID;

#RIGHT JOIN WITH NULL ON LEFT : ONLY NOT MATHCING OF RIGHT
SELECT * FROM EMP E RIGHT JOIN DEPT D ON E.DEPTID=D.DEPTID WHERE ;

select * from emp e 
left join dept d on e.deptid=d.deptid
where d.deptid is not null;